/* this is a DISPLAY type specific file */

#include "types.h"
#include "genlit.h"
#include "displit.h"
#include "genfont.h"

#define DIGITS_IN_TEXT								 40
#define	DISPLAYS_IN_SYSTEM							1
#define MODULES_IN_DISPLAY						  4
#define DIGITS_IN_MODULE		 					  10
#define BLOCKS_IN_DIGIT 							 21
#define MODULE_HW_WIDTH	(DIGITS_IN_MODULE * 14)

/***/
#define BLOCKS_IN_TEXT (DIGITS_IN_TEXT * BLOCKS_IN_DIGIT)
/***/
#define MODULES_IN_SYSTEM (DISPLAYS_IN_SYSTEM * MODULES_IN_DISPLAY)
#define DIGITS_IN_SYSTEM (MODULES_IN_SYSTEM * DIGITS_IN_MODULE)
#define BLOCKS_IN_SYSTEM (DIGITS_IN_SYSTEM * BLOCKS_IN_DIGIT)
/***/
#define DIGITS_IN_DISPLAY (MODULES_IN_DISPLAY * DIGITS_IN_MODULE)
#define BLOCKS_IN_DISPLAY (DIGITS_IN_DISPLAY * BLOCKS_IN_DIGIT)
/***/
#define BLOCKS_IN_MODULE (DIGITS_IN_MODULE * BLOCKS_IN_DIGIT)
/***/

const	UINT wDIGITS_IN_TEXT = DIGITS_IN_TEXT;
const UINT wBLOCKS_IN_TEXT = BLOCKS_IN_TEXT;

const UINT wMODULES_IN_SYSTEM = MODULES_IN_SYSTEM;
const UINT wDIGITS_IN_SYSTEM = DIGITS_IN_SYSTEM;
const UINT wBLOCKS_IN_SYSTEM = BLOCKS_IN_SYSTEM;

const UINT wMODULES_IN_DISPLAY = MODULES_IN_DISPLAY;
const UINT wDIGITS_IN_DISPLAY = DIGITS_IN_DISPLAY;
const UINT wBLOCKS_IN_DISPLAY = BLOCKS_IN_DISPLAY;

const UINT wDIGITS_IN_MODULE = DIGITS_IN_MODULE;
const UINT wBLOCKS_IN_MODULE = BLOCKS_IN_MODULE;

const UINT wBLOCKS_IN_DIGIT = BLOCKS_IN_DIGIT;

const UINT wMODULE_HW_WIDTH = MODULE_HW_WIDTH;  

/* defined here to reserve exact amount of memory */

UINT8 *psStartsOfFonts[DIGITS_IN_TEXT + ONE];
FontStruc Fonts[DIGITS_IN_TEXT + ONE];
UINT8 sSpaceString[DIGITS_IN_SYSTEM];


