/* this file is common to all display types */
#include "types.h"
#include "genlit.h"


extern UINT CONSTfontDivTbl[];


extern const UINT wDIGITS_IN_TEXT;
extern const UINT wBLOCKS_IN_TEXT;

extern const UINT wMODULES_IN_SYSTEM;
extern const UINT wDIGITS_IN_SYSTEM;
extern const UINT wBLOCKS_IN_SYSTEM;

extern const UINT wMODULES_IN_DISPLAY;
extern const UINT wDIGITS_IN_DISPLAY;
extern const UINT wBLOCKS_IN_DISPLAY;

extern const UINT wDIGITS_IN_MODULE;
extern const UINT wBLOCKS_IN_MODULE;

extern const UINT wBLOCKS_IN_DIGIT;


extern const UINT wMODULE_HW_WIDTH;  

extern UINT8 *psStartsOfFonts[];
extern FontStruc Fonts[];
extern UINT8 sSpaceString[];

